[package]
authors = ["Michael Rosenberg", "micro@fastmail.com"]
name = "dudect-bencher"
version = "0.3.1"
edition = "2018"

license = "MIT"

repository = "https://github.com/rozbb/dudect-bencher/"
documentation = "https://docs.rs/dudect-bencher/"

description = "An implementation of the DudeCT constant-time function tester"

keywords = ["constant", "constant-time", "crypto", "benchmark"]

[dependencies]
clap = "2.25"
ctrlc = "3.0"
rand = "0.6"
rand_chacha = "0.1"

[dev-dependencies]
rand = "0.6"
